name: Linux Clang

on:
  pull_request:
    types: [ready_for_review, synchronize]
  push:
    branches:
      - main

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: release
  BUILD_PLATFORM: x64

jobs:
  build:
    name: Linux Clang Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
    - uses: actions/checkout@v5

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev

    - name: Generate premake5 solution
      working-directory: ${{env.SOLUTION_FILE_PATH}}
      run: ./gen_proj_linux.sh

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: make -j$(nproc) config=${{env.BUILD_CONFIGURATION}}_${{env.BUILD_PLATFORM}}
